### PR TITLE
Deprecate spiderlets

### PR DESCRIPTION
**Pull request by rdowinton**
Updated documentation to mention spiderlets are now deprecated

### CODE REVIEW

**Comment by kalessin** [comment]
which is now the substitute?

**Comment by kalessin** [comment]
also, this entire repository is already deprecated, right?

**Comment by pablohoffman** [comment]
there is no substitute, spiderlets won't be supported in portia

**Comment by dangra** [comment]
I thought this repo was frozen, why the changes to this repository?

**Comment by pablohoffman** [comment]
This was probably just to emphasize that spiderlets are deprecated, for someone that happened to land on that page without seeing that the project was frozen.

I'd be ok about closing this project on github to avoid confusions.

**Comment by kalessin** [comment]
Yes, +1 to close this project.

**Comment by dangra** [comment]
The only thing we can do is remove the repository, there is nothing like a read-only mode in github.

**Comment by pablohoffman** [comment]
what if we recreate the repo with just a README file that points to portia?

**Comment by dangra** [comment]
or just remove all files in a commit plus README link to portia.

We keep the history but make it clear the repo is closed.

2015-04-27 10:33 GMT-03:00 Pablo Hoffman <notifications@github.com>:

**Comment by pablohoffman** [comment]
even better, let's do it!

**Comment by kalessin** [comment]
+1

**Comment by pablohoffman** [comment]
done in https://github.com/scrapy/slybot/commit/47ce5afa740f99943a6bbd3bdfc5d624d7621f61

**Comment by dangra** [comment]
:+1:

2015-04-27 14:01 GMT-03:00 Pablo Hoffman notifications@github.com:

**Pull request merged**
